### ISSUE TITLE
Add project info to readme

### ISSUE THREAD

**Issue by Robbedoes24** [vives-project-xp/MusicLightTiles#29]
Update readme with more info about the project.

**TODO:**
- [ ] Add project canvas
- [ ] Better layout/formating
- [ ] Examples/pictures

**Comment by Robbedoes24** [comment]
TODO:

- [ ] Add project canvas
- [ ] Better layout/formating
- [ ] Examples/pictures
- [ ]
